export const locations = {
  "Buenos Aires": {
    "Capital Federal": [
      "Parque Patricios",
      "Recoleta",
      "Palermo",
      "San Nicolás",
      "Belgrano",
      "Caballito",
      "Flores",
      "Villa Urquiza",
      "Almagro",
      "Boedo",
      "Nuñez",
      "San Telmo",
    ],
    "Zona Norte": [
      "San Isidro",
      "Vicente López",
      "Tigre",
      "Escobar",
      "San Fernando",
      "Malvinas Argentinas",
      "Pilar",
      "Jose C. Paz",
    ],
    "Zona Oeste": [
      "La Matanza",
      "Tres de Febrero",
      "Hurlingham",
      "Morón",
      "Ituzaingó",
      "Merlo",
      "Moreno",
      "General Rodríguez",
      "Marcos Paz",
    ],
    "Zona Sur": [
      "Avellaneda",
      "Lanús",
      "Lomas de Zamora",
      "Esteban Echeverría",
      "Ezeiza",
      "San Vicente",
      "Presidente Perón",
      "Almirante Brown",
      "Quilmes",
      "Berazategui",
      "Florencio Varela",
    ],
    "Costa Atlantica": [
      "Mar del Plata",
      "Pinamar",
      "Villa Gesell",
      "Miramar",
      "Necochea",
    ],
  },
  Mendoza: {
    "Gran Mendoza": [
      "Mendoza Capital",
      "Godoy Cruz",
      "Guaymallén",
      "Las Heras",
      "Maipú",
      "Luján de Cuyo",
    ],
    "Zona Este": ["San Martín", "Rivadavia", "Junín", "Santa Rosa", "La Paz"],
    "Zona Sur": ["San Rafael", "General Alvear", "Malargüe"],
    "Zona Valle de Uco": ["Tunuyán", "Tupungato", "San Carlos"],
  },
  Cordoba: {
    "Cordoba Capital": [
      "Córdoba Capital",
      "Nueva Córdoba",
      "Cerro de las Rosas",
      "Alta Córdoba",
      "General Paz",
      "Güemes",
      "Jardín",
    ],
    "Sierras Chicas": [
      "Villa Allende",
      "La Calera",
      "Río Ceballos",
      "Unquillo",
      "Mendiolaza",
    ],
    Punilla: [
      "Villa Carlos Paz",
      "Cosquín",
      "La Falda",
      "Dolores",
      "Capilla del Monte",
      "Valle Hermoso",
    ],
    Sur: ["Rio Cuarto", "Villa María", "Bell Ville", "Laboulaye"],
    Norte: ["Jesus Maria", "Villa del Totoral", "Dean Funes", "San Francisco"],
  },
  "Santa Fe": {
    "Santa Fe Capital": ["Santa Fe", "Santo Tome", "Sauce Viejo"],
    Rosario: ["Rosario", "Funes", "Roldán", "Granadero Baigorria", "Perez"],
    Sur: ["Venado Tuerto", "Rufino", "Firmat", "Villa Cañas"],
    Norte: ["Reconquista", "Rafaela", "Vera", "Tostado"],
    Centro: ["San Jorge", "Sunchales", "Esperanza", "San Cristobal"],
  },
};
